config/routes.rb
Rails.application.routes.draw do
  root 'games#index'
  resources :games
  post "/games/save", to: "games#save"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :turns

  def self.winning_combos
    [
      [0, 1, 2],
      [3, 4, 5],
      [6, 7, 8],
      [0, 3, 6],
      [1, 4, 7],
      [2, 5, 8],
      [0, 4, 8],
      [2, 4, 6]
    ]
  end

end

app/models/turn.rb
class Turn < ApplicationRecord
  belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]
  before_action :accept_all_params

  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/1
  def show
  end

  # GET /games/new
  def new
    @game = Game.new

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: "Game was successfully created." }
      else
        # TODO: replace with a generic error page
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # GET /games/1/edit
  # def edit
  # end

  # POST /games
  # def create
  #   @game = Game.new(game_params)

  #   respond_to do |format|
  #     if @game.save
  #       format.html { redirect_to @game, notice: "Game was successfully created." }
  #       format.json { render :show, status: :created, location: @game }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @game.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def save
    @game = Game.find(params[:id])

    tile = []
    tiles = ['h0', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'h7', 'h8']
    params.each do |key, val|
      if tiles.include? key
        unless val.empty?
          tile << key[-1]
        end
      end
    end

    if tile.length > 1
      # TODO: Should do better than this...
      raise "You can't take more than one turn at a time."
    end

    turn = Turn.new(tile: tile[0], player: @game.turn, game_id: @game.id)
    turn.save

    total_turns = Turn.select(:tile).where(game_id: @game.id).length
    player_turns = Turn.select(:tile).where(game_id: @game.id, player: @game.turn).order(:tile).map(&:tile)

    if(player_turns.length >= 3)
      Game.winning_combos.each do |combo|
        diff = combo - player_turns
        if diff.length == 0
          message = 'Player ' + @game.turn + ' has won the game!'
          @game.status = message
          @game.save
          redirect_to @game, notice: message
          return
        end
      end
    end

    if total_turns >= 9 # Should never actually be greater than 9...
      message = 'The game has ended in a draw :('
      @game.status = message
      @game.save
      redirect_to @game, notice: message
      return
    end

    @game.turn = @game.turn == 'X' ? 'O' : 'X'
    @game.save

    redirect_to @game, notice: "Game was successfully updated."
    return
  end

  # PATCH/PUT /games/1
  def update
    byebug

    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: "Game was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:status, :turn)
    end

    def turn_params
      params.require(:turn).permit(:h0, :h1, :h2, :h3, :h4, :h5, :h6, :h7, :h8)
    end

    def accept_all_params
      params.permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :turn %>
    <%= form.text_field :turn %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Game ID</th>
      <th>Turn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.id%></td>
        <td><%= game.turn %></td>
        <% if game.status == 'in_progress' %>
          <td><%= link_to 'Continue Playing', game %></td>
        <% else %>
          <td><%= game.status %></td>
        <% end %>

        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @game.status %>
</p>

<% if @game.status == 'in_progress' %>

  <%= form_with(url: games_save_path, html: {id: 'tictacform'}) do %>
    <input type="hidden" name='id' value='<%=@game.id%>'>
    <% if @game.turn == 'X' %>
      It's Player X's Turn<br>
    <% else %>
      It's Player O's Turn<br>
    <% end %>

    <%
      for i in 0..8 do
        if i % 3 == 0%>
          <br>
        <%end

        val = ''
        @game.turns.each do |turn|
          if turn.tile == i
            val = turn.player
            break
          end
        end%>
        <input type="button" class="tictac" onclick="buttonClick('<%=i%>', '<%=@game.turn%>')" id='b<%=i%>' name='b<%=i%>' value='<%=val%>' <%=val.empty? ? '' : 'disabled'%>>
        <input type="hidden" id='h<%=i%>' name='h<%=i%>' value='<%=val%>' <%=val.empty? ? '' : 'disabled'%>>
      <%end
    %><br><br>

    <input type="submit" name='b1'>
  <% end
end%>

<%= link_to 'Home', games_path %>
<script>
  function buttonClick(id, val) {
    document.getElementById('b' + id).value = val;
    document.getElementById('h' + id).value = val;
    document.getElementById("tictacform").submit();
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tictactoe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>